<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
 <script>  
 //$(function (){  
   // $('#numero').number( true, 2 );
 //})
 </script>

<div class="row">    
<div class="col-sm-2">Salario $:<br />
<?php
    $name = $form->get('valorS')->setAttribute("id","numero")->setAttribute("class","numeric");
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>    
</div>
<br /> 
<div class="row">    
<div class="col-sm-1">Codigo $:<br />
<?php
    $name = $form->get('codigo')->setAttribute("id","codigo");
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>   
</div>    
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    

