<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>
      <?php
       $select = $form->get('estado');
       echo $formLabel->openTag().'Estado';
       echo $formLabel->closeTag();
       echo $this->formSelect($select);
       echo $this->formElementErrors($select);
      ?>

<?php echo $this->render('layout/tabla_c') ?>

    <?php
    $datos = $this->datos ;
    if ( $escala == 0  ) // No maneja escala salarial, si no sueldos fijos
       $datos = $this->datosE ;
     $i = 1;
     foreach ($datos as $dato){
       if ( $escala == 0  ) // No maneja escala salarial, si no sueldos fijos 
       {
          $idI = $i;}
       else
          $idI = $dato['id']; 
      ?>
        <tr>
            <td><?php
             if ( $escala == 1  ) // No maneja escala salarial, si no sueldos fijos 
                echo $dato["codigo"];
             else
                echo $i; $i++; ?></td>
            <td>                
               <?php                 
                  $name = $form->get('numero')->setAttribute("value",$dato["salario"])
                                 ->setAttribute("class","numero")
                                 ->setAttribute("id",'sa'.$idI) 
                                 ->setAttribute("name",'sa'.$idI) 
                                 ->setAttribute("readonly",true);            
                  echo $this->formInput($name);
                  echo $this->formElementErrors($name);     
               ?>                                                
            </td>                        
            <td>
               <?php            
                 $name = $form->get('diasVac')->setAttribute("value",0)
                                 ->setAttribute("id",  $idI)
                                 ->setAttribute("name", "por".$idI);
                 echo $this->formInput($name);
                 echo $this->formElementErrors($name);            
                 if ( $dato["porInc"]>0 )
                     echo $dato["porInc"].' %';
               ?>                
            </td>            
            <td>
               <?php 
                  $valor = 0;                
                  if ( $dato["salarioNue"] > 0 )
                     $valor = $dato["salarioNue"];                                 

                  $name = $form->get('diasVacP')->setAttribute("value",$valor)
                                 ->setAttribute("id",'nsa'.$idI) 
                                 ->setAttribute("name",'nsa'.$idI);            
                  echo $this->formInput($name);
                  echo $this->formElementErrors($name);     
               ?>                                
            </td>
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>

<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')->setAttribute("id","generar")) ?>
</div>         
        
<?php echo $this->form()->closeTag() ?>

<script>  
 $(function (){  
    $('.span5').number( true, 2 );
    $('.span6').number( true );
    $('.numero').number( true );    
 })
 
 $('.span5').focusout(function(){  
   var id   = $(this).attr('id');  
   var porc = $("#"+id).val();
   var sal  = parseInt( $("#sa"+id).val() ) ;
   var nsal =  ( parseInt ( (porc/100) * sal) ) + sal  ;
   $("#nsa"+id).val(nsal);
   
 })
 </script>



<?php echo $this->render('layout/iregresar') ?>    

