<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
<div class="col-sm-4">Nombre:<br />
<?php
    $name = $form->get('nombre');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
</div>    

<hr />

<div class="row">    
<div class="col-sm-4">Codigo de cuenta:<br />
<?php
    $name = $form->get('codigo');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
</div>    

<hr />

<div class="row">    
<div class="col-sm-2">
<?php
    $select = $form->get('check1');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>Maneja terceros
</div>     
    
<div class="col-sm-2">
<?php
    $select = $form->get('check2');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>Maneja centro de costos    
</div>    

<div class="col-sm-2">
<?php
    $select = $form->get('check3');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>Es gastos    
</div>    

<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<hr />    
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    