<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.$this->lin,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<input type="hidden" name="campo" id="campo" value='1' />    
<?php echo $this->form()->closeTag() ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.$this->lin,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<div class="row">    
<div class="col-sm-4">Empelado:<br />
<?php
    $select = $form->get('idEmp');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>

<div class="col-sm-4">Tipo:<br />
<?php
    $select = $form->get('tipo');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>    
</div>

<br />
<div>
  <?php echo $this->formElement($form->get('agregar')) ?>
</div>  
<hr />
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<input type="hidden" name="campo" id="campo" value='2' />
<?php echo $this->form()->closeTag() ?>

<div id="dialog"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ 
        $id=$dato["id"];
        ?>
        <tr>
            <td><?php echo $dato["CedEmp"] ?></td>
            <td><?php echo $dato["nombre"].' '.$dato["apellido"] ?></td>
            <td><?php echo $dato["tipo"] ?></td>
            <td><?php echo number_format( $dato["porcentaje"] )?></td>            
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>i/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/iitems') ?> </a>
            </td>                                               
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>id/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php         
$this->ncol='null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>        
        
<?php
//$this->lin= $id ;
echo $this->render('layout/iregresar') ?> 