<?php echo $this->render('layout/titulo') ?>

<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>
<div id="dialog"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>            
            <td><?php echo $dato["codigo"] ?></td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>i/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/iitems') ?> 
                <?php if ($dato['numSuc']) echo '('.$dato['numSuc'].')';  ?>
                </a>
                
            </td>            
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
   
<?php
// Variables para envio de datos excel maestro
$this->spdf      = 1;// Activa la salida por PDf
$this->modelo    = 'new \Nomina\Model\Entity\Bancos($con)';// Modelo de consulta
$this->funcion   = '$m->getRegistro()';
$this->columnas  = "CODIGO, BANCO";// Columnas
$this->datos     = "id, nombre";// Datos de impresion
$this->filtros   = 1;
echo $this->render('layout/tabla_p') ?>        
<?php 
$this->ncol='null,null,null,';
echo $this->render('layout/tabla_tb') ?>        