<?php echo $this->render('layout/titulo') ?>

<div class="tabbable">
  <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
	<li class="active">
	    <a data-toggle="tab" href="#datos">Documento de incapacidad</a>
	</li>
	<li>
	    <a data-toggle="tab" href="#prorrogra">Prórrogas <?php if ($this->datosTp['numP']>0) echo '('.$this->datosTp['numP'].')'; ?>  </a>
	</li>

  </ul>

  <div class="tab-content"> 
      
      <div id="datos" class="tab-pane in active"><!-- DATOS BASICOS -->             

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a/'.$this->id,
    'method' => 'post',
    'id'     => 'formGuaradar'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">
<div class="col-sm-4">Empleado:<br />    
    <?php
    $select = $form->get('idEmp');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div> 
<div class="col-sm-4">Tipo de incapacidad:<br />
<?php
    $select = $form->get('idInc');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div> 
<div class="col-sm-2">Estado del documento:<br />
<?php
       $select = $form->get('estado');
       echo $this->formSelect($select);
       echo $this->formElementErrors($select);
?>        
</div> 
</div>     
<br />
<div class="row">
<div class="col-sm-2">Desde el:<br />    
<?php
    $name = $form->get('fechaIni');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);?>
</div>    
<div class="col-sm-2">Hasta el:<br />    
<?php    
    $name = $form->get('fechaFin');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);    
?>
</div>
     <div class="col-sm-4">Codigo de enfermedad:<br />
<?php
    $select = $form->get('tipo2');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>

      </div>
</div>
<hr />
<div class="control-group">
    <?php echo ($this->formRow($form->get('comen'))); ?>
</div>  

<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

</div><!-- FIN DATOS BASICOS -->    


<div id="prorrogra" class="tab-pane in active"><!-- PRORROGRA-->              

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'ap/'.$this->id,
    'method' => 'post',
    'id'     => 'formGuaradar'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<?php    
    $name = $form->get('id2'); // id de la incapacidad
    echo $this->formInput($name);    
?>    
<?php    
    $name = $form->get('id3');// id del empleado
    echo $this->formInput($name);    
?>    

<div class="row">
<div class="col-sm-2">Nueva prórroga desde el:<br />    
<?php    
    $name = $form->get('fecIng');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);    
?>
</div>

<div class="col-sm-2">hasta el:<br />    
<?php    
    $name = $form->get('fecIng2');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);    
?>
</div>
  <div class="col-sm-4">Observación:<br />    
    <?php echo ($this->formRow($form->get('comenN'))); ?>
</div>
<?php echo $this->formElement($form->get('agregar2')) ?>
</div>
<hr />

<?php // Datos de las prorrogras
$this->th3  = "Prórrogas";
echo $this->render('layout/h3rojo') ?>

<?php echo $this->form()->closeTag(); $num = 1; ?>


<table class="table table-striped table-bordered table-hover" id="table_report">
 <thead>
  <tr>
    <th width="11%">id</th>
    <th width="11%">Fecha de registro</th>
    <th width="11%">Fecha de inicio</th>
    <th width="11%">Fecha final</th>    
    <th width="11%">Observación</th>        
    <th width="11%">Eliminar</th>        
  </tr>
 </thead>
    <?php foreach ($this->datosP as $dato){ ?>
        <tr>
            <td><?php echo $num; $num++; ?></td>                            
            <td><?php echo $dato["fecha"]; ?></td>                    
            <td><?php echo $dato["fechai"]; ?></td>            
            <td><?php echo $dato["fechaf"]; ?></td>            
            <td><?php echo $dato["comen"]; ?></td>                        
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>pd/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>




</div> <!-- FIN PRORROGRA -->                                             
</div> 

<?php echo $this->render('layout/iregresar') ?> 
   
    
<div id="resultado"></div>    
<script>         
$( "#idInc" ).change(function(){ 
 //   alert(1)
});    
//// Buscar fecha del periodo /////
$( "#idEmp" ).change(function(){ 
   var a = $("#idInc").val(); 
   var b = $("#idEmp").val(); 
   var c = $("#fechaIni").val(); 
   
   // Valdiar periodo
   var parametros = {
       "idInc" : a,                
       "idEmp"   : b,                
       "fechaIni": c,                
   }; 
     $.ajax({
        data:  parametros,
        url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>g',
        type:  'post',
        beforeSend: function () {
           $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Por favor espere...');
        },                
        success:  function (response) {
           $("#resultado").html(response);  
      }
   });          
});
$( "#idInc" ).change(function(){ 
   var a = $("#idInc").val(); 
   var b = $("#idEmp").val(); 
   var c = $("#fechaIni").val();    
   
   // Valdiar periodo
   var parametros = {
       "idInc" : a,                
       "idEmp"   : b,                
       "fechaIni": c,                
   }; 
     $.ajax({
        data:  parametros,
        url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>g',
        type:  'post',
        beforeSend: function () {
           $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Por favor espere...');
        },                
        success:  function (response) {
           $("#resultado").html(response);  
      }
   });           
});
$( "#fechaIni" ).change(function(){ 
   var a = $("#idInc").val(); 
   var b = $("#idEmp").val(); 
   var c = $("#fechaIni").val();    
   
   // Valdiar periodo
   var parametros = {
       "idInc" : a,                
       "idEmp"   : b,                
       "fechaIni": c,                
   }; 
     $.ajax({
        data:  parametros,
        url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>g',
        type:  'post',
        beforeSend: function () {
           $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Por favor espere...');
        },                
        success:  function (response) {
           $("#resultado").html(response);  
      }
   });           
});

$( "#formGuaradar" ).submit(function( event ) {

   var verPer = $("#verPer").val(); 
   var idEmp = $("#idEmp").val();   
   var b = $("#fechaIni").val();    
   var c = $("#fechaFin").val();       

   if ( b == ''   ) // Si la fecha del sistema es menor que la fecha de inicio del periodo activo
   {
      alert('No se puede guardar el documento, seleccione la fecha');
      return false;
   }

   if ( c == ''   ) // Si la fecha del sistema es menor que la fecha de inicio del periodo activo
   {
      alert('No se puede guardar el documento, seleccione la fecha');
      return false;
   }

   if ( idEmp == ''   ) // Si la fecha del sistema es menor que la fecha de inicio del periodo activo
   {
      alert('No se puede guardar el documento, debe seleccionar al empleado');
      return false;
   }

   if ( verPer == 1  ) // Si la fecha del sistema es menor que la fecha de inicio del periodo activo
   {
     // alert('No se puede guardar el documento, la fecha del sistema es menor a la del periodo activo');
     // return false;
   }

});
</script>