<?php echo $this->render('layout/titulo') ?>


<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nomTnom"] ?></td>
            <td><?php echo $dato["nomGrupo"] ?></td>
            <td><?php echo $dato["fechaI"] ?></td>
            <td><?php echo $dato["fechaF"] ?></td>
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php echo $this->render('layout/iregresar') ?>