<?php echo $this->render('layout/titulo') ?>

<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>
<div id="dialog"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php 
            switch ($dato["tipo"]) {
                case 1:
                     echo 'Manual';
                    break;
                case 2:
                     echo 'Intervalo de días';
                    break;
                case 3:
                     echo 'Periodos en el año';
                    break;
            } 
            ?></td>
            <td><?php 
            if ($dato["fecIemp"]==1) {
                echo 'inicio de labores del empleado';}
            else{
                echo $dato["fecha"];
            } 
            ?></td>            
            <td><?php echo $dato["valor"] ?></td>            
            <td>
             <?php if ($dato["fecIemp"]==0) { ?>   
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>i/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/iitems') ?> </a>
             <?php } ?>      
            </td>            
            <td>
             <?php if ($dato["fecIemp"]==0) { ?>                   
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>c/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/icalendar') ?> </a>
             <?php } ?>                   
            </td>                                    
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php 
$this->ncol='null,null,null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>