<?php echo $this->render('layout/titulo') ?>

<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>
<div id="dialog"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["id"]; ?></td>            
            <td><?php echo $dato["nombre"]; 
            if ($dato["codigo"] != null)
                echo ' ('.$dato["codigo"].')';
                    ?>                
            </td>
            <td><?php echo $dato["estDoc"]; ?></td>    
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php
// Variables para envio de datos excel maestro
$this->spdf      = 1;// Activa la salida por PDf
$this->modelo    = 'new \Nomina\Model\Entity\Cencostos($con)';// Modelo de consulta
$this->funcion   = '$m->getRegistro()';
$this->columnas  = "CODIGO, CENTRO DE COSTO";// Columnas
$this->datos     = "id, nombre";// Datos de impresion
$this->filtros   = 1;
echo $this->render('layout/tabla_p') ?>        
<?php 
$this->ncol='null,null,null,';
echo $this->render('layout/tabla_tb') ?>        
    
