<?php 
echo $this->render('layout/titulo') ?>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>                                    
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> 
                    <?php echo $this->render('layout/ipersonal') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
   
<?php 
$this->ncol='null,';
echo $this->render('layout/tabla_tb') ?>   