<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a/'.$this->id,
    'method' => 'post',
    'id' => 'formGuardar',
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<?php    
    $name = $form->get('id'); // id de la matriz 
    echo $this->formInput($name);    
?>
<?php    
    $name = $form->get('id2'); // Tipo de matriz
    echo $this->formInput($name);    
?>
 
<div class="row">    
  <div class="col-sm-4">Empleados que hacen parte de este grupo :<br />
      <?php
      $select = $form->get('idEmp')->setAttribute("id","idEmp");
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
      ?>
  </div>
  <div class="col-sm-2">Fecha de ingreso::<br />
  <?php
    $name = $form->get('fecDoc');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
  ?>
  </div>         
  <div class="col-sm-4">
    <?php echo $this->formElement($form->get('send')) ?>    
  </div>
       
 </div>
 
<hr />
              

 <?php 
 $this->th3='Empleados ';
 echo $this->render('layout/h3rojo') ?>

<?php echo $this->form()->closeTag() ?>


<!-- LISTADO DE NOVEDADES EN CUSRO -->
<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["CedEmp"] ?></td>                        
            <td><?php echo $dato["nombre"].' '.$dato["apellido"] ?></td>            
            <td><?php echo $dato["fecIng"] ?></td>                                    
            <td><?php echo $dato["fecha"] ?></td>                                                
            </td>                                    
            <td>
                <a href="<?php echo $this->basePath() ?><?php $this->idEli = $dato["id"]; echo $this->lin?>id/<?php echo $dato["id"]?>"> 
                    <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php

echo $this->render('layout/tabla_p') ?> 
   
<?php 
$this->ncol='null,null,null,';
echo $this->render('layout/tabla_tb') ?>   

<?php echo $this->render('layout/iregresar') ?>    

