<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a/'.$this->id,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
  <div class="col-sm-4">Tipo de nómina:<br />              
<?php
    $select = $form->get('tipo');
    $select->setAttribute('id', 'tipo');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
  </div> 
  <div class="col-sm-4">Grupo de nómina:<br />              
<?php
    $select = $form->get('idGrupo')->setAttribute("id","idGrupo");
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
    ?>
</div>    
</div>    
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>

<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    
