<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
<div class="col-sm-4">Nombre:<br />
<?php
    $name = $form->get('nombre');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
</div>    
<div class="row">    
<div class="col-sm-4">La entidad pagará a partir del día:<br />
<?php
    $name = $form->get('numero');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>        
</div>
<div class="col-sm-4">Numero de dias fijos:<br />
<?php
    $name = $form->get('valor');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>        
</div>
</div>    
<hr />
<div class="row">    
<div class="col-sm-4">Conceptos de nomina asumidos empresa:<br />
    <?php
      $select = $form->get('idConcM');
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
   ?>   
</div>
</div>
<div class="row">    
<div class="col-sm-4">Conceptos de nomina asumidos entidad:<br />
    <?php
      $select = $form->get('idConcM2');
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
   ?>   
</div>
</div>

<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    